### ISSUE TITLE
Region of interest intersetion overlapping 

### ISSUE THREAD

**Issue by srabanroy** [tarbiarswat/CSE499-CVindicate-Driving-Companion#2]
I tried to resolve the issue but the rectangular lines are overlapping over and over again, I think the camera position is causing some problem here or the provided region of interest intersection graph is not properly plotted. Please try to solve this. Thank you.

**Comment by kaniz07** [comment]
As the position of the camera was changed, that is why the region of interest was overlapped. So i have recreated the graph plotting of the region of interest and have to modify the value of the source points to have the expected result. The raised issue is solved now.
