### ISSUE TITLE
Pointer exception error in histrogram

### ISSUE THREAD

**Issue by kaniz07** [tarbiarswat/CSE499-CVindicate-Driving-Companion#3]
I am facing a problem of exception in the final frame. The summation of the  given value  of the frame range is crossing the actual frame range. I have tried some modified values to balance the range but still have "exception error".

**Comment by tarbiarswat** [comment]
So basically what happened, the regional image size and the output image size in the histogram was not the same. As the histogram will inherit the bird's eye view, the size of the perspective will be:

```
Matrix = getPerspectiveTransform(Source, Destination);
warpPerspective(frame, framePers, Matrix, Size(400,240));
```
	
	
and our default size is 360 x 240. whereas somewhere this was 400 x 240 in your error. Using all over the 360x240 and the correct cropping frame will solve this issue further.
